<?php
namespace App\Http\Middleware;
use Closure;
use Illuminate\Foundation\Http\Middleware\TrimStrings as Middleware;

class SessionTimeOut extends Middleware{
    public function handle($request, Closure $next)
    {
        if (now()->diffInMinutes(session('lastActivityTime')) >= (31) ) {  // also you can this value in your config file and use here
            if (auth()->check()) {
                $user = auth()->user();
                auth()->logout();
                session()->forget('lastActivityTime');
                return redirect(route('login'));
            }
        }
        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }

}